#! Nomeando o workflow
name: NASA Project CI
#! Quando o workflow irá funcionar
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
#! O que o programa vai rodar
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.JS version 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm run build --prefix client